const navItems = [{ label: 'Home', href: 'index.html' }, { label: 'About', href: 'about.html' }, { label: 'Projects', href: 'projects.html' }, { label: 'Skills', href: 'skills.html' }, { label: 'Experience', href: 'experience.html' }, { label: 'Certifications', href: 'certifications.html' }, { label: 'Contact', href: 'contact.html' }];
const currentPage = window.location.pathname.split('/').pop() || 'index.html';
const header = document.querySelector('#site-header');
if (header) { header.innerHTML = `<header class="site-nav"><a class="brand" href="index.html">RAVI TEJA</a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="nav-links" aria-label="Primary navigation">${navItems.map(item => `<a href="${item.href}" class="${currentPage === item.href ? 'active' : ''}">${item.label}</a>`).join('')}</nav><a class="nav-resume" href="resume/RAVI_TEJA_RESUME.pdf" download>Download Resume</a></header>`; }
const footer = document.querySelector('#site-footer');
if (footer) { footer.innerHTML = `<footer class="site-footer"><div class="footer-inner"><div class="footer-brand">RAVI TEJA DARABATHULA<span>Computer Science &amp; Engineering</span></div><nav class="footer-nav" aria-label="Footer navigation">${navItems.map(item => `<a href="${item.href}">${item.label}</a>`).join('')}</nav><div class="footer-links"><a href="https://www.linkedin.com/in/ravi-teja-414540312" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="mailto:drt90619@gmail.com">Email ↗</a></div></div><div class="copyright">© 2026 Ravi Teja Darabathula. All rights reserved.</div></footer>`; }
const nav = document.querySelector('.site-nav'); const menuToggle = document.querySelector('.menu-toggle'); const navLinks = document.querySelector('.nav-links');
menuToggle?.addEventListener('click', () => { const open = navLinks.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', String(open)); menuToggle.setAttribute('aria-label', open ? 'Close navigation' : 'Open navigation'); });
navLinks?.querySelectorAll('a').forEach(link => link.addEventListener('click', () => { navLinks.classList.remove('open'); menuToggle?.setAttribute('aria-expanded', 'false'); }));
const backTop = document.querySelector('.back-top');
window.addEventListener('scroll', () => { nav?.classList.toggle('scrolled', window.scrollY > 20); backTop?.classList.toggle('visible', window.scrollY > 500); }, { passive: true });
backTop?.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
const revealObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); revealObserver.unobserve(entry.target); } }), { threshold: .12 });
document.querySelectorAll('.reveal').forEach(element => revealObserver.observe(element));
const filterButtons = document.querySelectorAll('.filter-button'); const projectCards = document.querySelectorAll('.large-project');
filterButtons.forEach(button => button.addEventListener('click', () => { filterButtons.forEach(item => item.classList.remove('active')); button.classList.add('active'); const filter = button.dataset.filter; projectCards.forEach(card => card.classList.toggle('hidden', filter !== 'all' && !card.dataset.category.split(' ').includes(filter))); }));
const projectDetails = { minicart: { title: 'MiniCart 2.0', text: 'A responsive e-commerce web application focused on practical browsing and ordering. It combines product filtering, price range selection, sorting, search, CSS Grid, Flexbox, DOM manipulation, responsive design, and WhatsApp order placement.' }, voting: { title: 'Online Voting System', text: 'A full stack voting application built with Python and Flask. The project explores email OTP authentication, vote tracking, multiple-vote prevention, an admin panel, real-time results, SQLite, Jinja2, and Flask-Mail.' }, weather: { title: 'Weather Forecast Application', text: 'A desktop application using Tkinter and the OpenWeatherMap API. Users can search for a city and view temperature, humidity, wind speed, and current conditions with input validation and error handling.' }, chatbot: { title: 'Rule-Based Chatbot', text: 'An interactive Q&A application built during an AI internship with Python and Panel. It uses predefined question-answer pairs, text input, button controls, conversation history, event-driven programming, and dynamic Markdown rendering.' } };
const modal = document.querySelector('#project-modal'); const modalTitle = document.querySelector('#modal-title'); const modalContent = document.querySelector('#modal-content');
document.querySelectorAll('.details-button').forEach(button => button.addEventListener('click', () => { const detail = projectDetails[button.dataset.project]; if (!detail || !modal) return; modalTitle.textContent = detail.title; modalContent.innerHTML = `<p>${detail.text}</p>`; modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; }));
const closeModal = () => { modal?.classList.remove('open'); modal?.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; }; document.querySelector('.modal-close')?.addEventListener('click', closeModal); modal?.addEventListener('click', event => { if (event.target === modal) closeModal(); }); document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); });
const form = document.querySelector('#contact-form');
form?.addEventListener('submit', event => { event.preventDefault(); let valid = true; form.querySelectorAll('input, textarea').forEach(field => { const error = field.parentElement.querySelector('.form-error'); let message = ''; if (!field.value.trim()) message = 'This field is required.'; else if (field.type === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value)) message = 'Please enter a valid email address.'; error.textContent = message; if (message) valid = false; }); const status = form.querySelector('.form-status'); if (valid) { status.textContent = 'Thanks for reaching out. This form is ready to connect to an email service.'; form.reset(); } else status.textContent = 'Please review the highlighted fields.'; });
